application/models.py
# db model classes
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from flask.ext.login import UserMixin, AnonymousUserMixin
from . import db, login_manager


class Permission:
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENTS = 0x08
    ADMINISTER = 0x80


class Role(db.Model):
    """docstring for Role"""
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role')

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.FOLLOW |
                     Permission.COMMENT |
                     Permission.WRITE_ARTICLES, True),
            'Moderator': (Permission.FOLLOW |
                          Permission.COMMENT |
                          Permission.WRITE_ARTICLES |
                          Permission.MODERATE_COMMENTS, False),
            'Administrator': (0xff, False)
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r][0]
            role.default = roles[r][1]
            db.session.add(role)
        db.session.commit()

    def __repr__(self):
        return '<Role {0}>'.format(self.name)


class User(UserMixin, db.Model):
    """docstring for User"""
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    address = db.Column(db.String)
    email = db.Column(db.String(64), unique=True, index=True)
    confirmed = db.Column(db.Boolean, default=False)

    password_hash = db.Column(db.String(128))

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['VOTEYOURKNOW_ADMIN']:
                self.role = Role.query.filter_by(permissions=0xff).first()
            else:
                self.role = Role.query.filter_by(default=True).first()

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False

        if data.get('confirm') != self.id:
            return False

        self.confirmed = True
        db.session.add(self)
        return True

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id})

    def reset_password(self, token, new_password):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        if data.get('reset') != self.id:
            return False
        self.password = new_password
        db.session.add(self)
        return True

    def can(self, permissions):
        return self.role is not None and \
            (self.role.permissions & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    def __repr__(self):
        return '<User {0}>'.format(self.username)


class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False


class SavedElection(db.Model):
    """docstring for SavedElection"""
    __tablename__ = 'saved_elections'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    election_name = db.Column(db.String)
    candidates = db.relationship('SavedCandidates')


class SavedCandidates(db.Model):
    """docstring for SavedCandidates"""
    __tablename__ = 'saved_candidates'
    id = db.Column(db.Integer, primary_key=True)
    election_id = db.Column(db.Integer, db.ForeignKey('saved_elections.id'))
    name = db.Column(db.String)
    party = db.Column(db.String)
    office = db.Column(db.String)


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

application/main/forms.py
from flask.ext.wtf import Form
from flask.ext.login import current_user
from wtforms import StringField, SubmitField, SelectField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import Required
from ..google_elections import get_elections_wtf
from ..models import SavedElection


# form classes
class AddressElectionLookup(Form):
    """lookup class for the election/address tuple"""

    address = StringField('Address:')
    # caller is responsible for providing choices.
    election = SelectField('Election: ', choices=[])
    saved_searches = QuerySelectField('Saved Searches: ',
                                      query_factory=lambda: SavedElection.query.filter_by(user_id=current_user.get_id()),
                                      get_pk=lambda a: a.id,
                                      get_label=lambda a: a.election_name,
                                      allow_blank=True)
    submit = SubmitField('Submit')

    def validate(self):
        if not Form.validate(self):
            return False
        result = True
        if bool(self.address.data) == bool(self.saved_searches.data):
            result = False
            if not bool(self.address.data):
                self.address.errors.append('Please enter an Address or select a Saved Election')
                self.saved_searches.errors.append('Please enter an Address or select a Saved Election')
            else:
                self.address.errors.append('Only Address or Saved Search may be used. They cannot be used together')
                self.saved_searches.errors.append('Only Address or Saved Search may be used. They cannot be used together')
        return result


class AddressLookup(Form):
    """lookup class for the address only"""
    address = StringField('Address:', validators=[Required()])
    submit = SubmitField('Submit')


class CandidateLookup(Form):
    """lookup class for candidate firstname and lastname"""
    firstname = StringField('First Name:', validators=[Required()])
    lastname = StringField('Last Name:', validators=[Required()])


class SaveElection(Form):
    election_name = StringField('Election Name:', validators=[Required()])

application/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from flask.ext.mail import Mail
from config import config
import logging

bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name):
    logging.debug('start application factory (create_app).....')
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    logging.debug('APP CONFIG: ' + str(app.config))

    config[config_name].init_app(app)  # does nothing, for now
    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    logging.debug('.....end application factory (create_app)')
    return app

application/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

# importing these views associate them with the blueprint!
from . import views, errors
from ..models import Permission


@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

application/main/views.py
from flask import render_template, session, redirect, url_for, current_app,\
    flash, request
from flask.ext.login import login_required, current_user
from .. import db
from . import main
from .forms import AddressElectionLookup, AddressLookup, CandidateLookup
from ..models import SavedElection, SavedCandidates
from ..google_elections import get_voterinfo, get_representativeinfo,\
    get_elections_wtf, flatten_voterinfo
from ..govtrak import get_bills_voted_on, get_bill
import json
import logging
from nameparser import HumanName
import ast


# routing
@main.route('/')
def show_landing_page():
    return render_template('landing_page.html')


@main.route('/voterinfo', methods=['GET', 'POST'])
def show_elections():
    """builds the voterinfo dictionary to display voting locations and
    candidates in an election

    We use the flatten_voterinfo method in the google_elections helper file
    to ensure we only show a single candidate per office, even if they are
    running under multiple parties
    """
    logging.debug('start show_elections')

    form = AddressElectionLookup()
    # to dynamically build the list, we pass in from the view.
    # see:
    # http://stackoverflow.com/questions/12850605/how-do-i-generate-dynamic-fields-in-wtforms/12854055#12854055
    form.election.choices =\
        get_elections_wtf(current_app.config['ELECTION_API_KEY'])

    if form.validate_on_submit():
        session['address'] = form.address.data
        session['election'] = form.election.data
        if form.saved_searches.data:
            session['saved_search'] = form.saved_searches.data.id
        else:
            session['saved_search'] = None

        return redirect(url_for('main.show_elections'))
    elif form.is_submitted():
        # clear the inputs if we tried to input, and failed.
        session['address'] = None
        session['election'] = None
        session['saved_search'] = None

    address = session.get('address')
    election = session.get('election')
    saved_search = session.get('saved_search')
    form.address.data = address
    form.election.data = election
    if saved_search:
        form.saved_searches.data = SavedElection.query.get(int(saved_search))
    else:
        form.saved_searches.data = None

    if election and address:
        logging.debug('START VOTERINFO')
        voterinfo = flatten_voterinfo(election,
                                      address,
                                      current_app.config['ELECTION_API_KEY'])
        if voterinfo.get("status") != "success":
            flash('Invalid Address or Election entered. Review and try again.')
        logging.debug('END VOTERINFO')
        return render_template('show_voterinfo.html',
                               voterinfo=voterinfo,
                               lookupform=form)
    elif saved_search:
        logging.debug('START SAVED SEARCH')
        election = SavedElection.query.get(int(saved_search))

        candidates = [row.__dict__ for row in election.candidates]
        logging.debug(candidates)
        logging.debug('END SAVED SEARCH')
        return render_template('show_saved_voterinfo.html',
                               voterinfo=candidates,
                               lookupform=form)

    return render_template('show_saved_voterinfo.html',
                           voterinfo={},
                           lookupform=form)


@main.route('/save_voterinfo', methods=['POST'])
@login_required
def save_voterinfo():
    # could have used WTForms to use this
    # and inject the list of candidates into it
    # ...felt like over kill
    selections = request.form.getlist("do_save")

    logging.debug("START NAMES...")
    vote_name = request.form['vote_name']
    existing_election = \
        SavedElection.query.filter_by(election_name=vote_name,
                                      user_id=current_user.id).first()
    if existing_election is None:
        existing_election = SavedElection(election_name=vote_name,
                                          user_id=current_user.id)
        db.session.add(existing_election)

    # existing_election.candidates.delete()
    for selection in selections:
        logging.debug(selection)
        # so dirty. gotta be a better way
        all_info = selection.split('|')
        candidate = all_info[0]
        # Full dict with details
        candidate_detail = ast.literal_eval(all_info[1])
        election = all_info[2]  # e.g. General
        office = all_info[3]  # e.g. Us Congress District 12
        level = all_info[4]  # e.g. federal
        logging.debug(all_info)

        existing_election.candidates.append(
            SavedCandidates(name=candidate,
                            party=', '.join(candidate_detail["party"]),
                            office=office))
    # need to commit here so we can pull the key
    db.session.commit()
    flash('Candiates Successfully Saved as "' + vote_name + '"')

    logging.debug("...END NAMES")
    session['address'] = None
    session['election'] = None
    session['saved_search'] = existing_election.id
    return redirect(url_for('main.show_elections'))


@main.route('/representatives', methods=['GET', 'POST'])
def show_representatives():
    form = AddressLookup()
    if form.validate_on_submit():
        session['address'] = form.address.data
        return redirect(url_for('main.show_representatives'))

    address = session.get('address')
    form.address.data = address
    representatives = {}
    if address:
        representatives =\
            get_representativeinfo(session.get('address'),
                                   current_app.config['ELECTION_API_KEY'])
        for representative in representatives['officials']:
            human_name = HumanName(representative['name'])
            logging.debug(human_name.as_dict())
            representative['first_name'] = human_name.first
            representative['last_name'] = human_name.last
    return render_template('show_representativeinfo.html',
                           representatives=representatives,
                           lookupform=form)


@main.route('/votehistory/<firstname>-<lastname>')
def show_votehistory(firstname, lastname):
    logging.debug('entering show_votehistory')
    form = CandidateLookup()
    votehistory = get_bills_voted_on(firstname, lastname, 10)
    for vote in votehistory:
        full_bill = get_bill(vote['vote']['related_bill'])
        if full_bill is not None:
            vote['full_bill'] = {}
            vote['full_bill']['title'] = full_bill['title']
            vote['full_bill']['link'] = full_bill['link']
    logging.debug('leaving show_votehistory')
    return render_template('show_representative_votehistory.html',
                           votehistory=votehistory,
                           lookupform=form)


@main.route('/votehistory')
def show_votehistory_blank():
    form = CandidateLookup()
    return render_template('show_representative_votehistory.html',
                           votehistory=None,
                           lookupform=form)

application/templates/landing_page.html
{% extends "layout.html" %}
{% block nav %}
  <ul class="nav nav-pills">
    <li class="active"><a href="{{ url_for('main.show_landing_page') }}" >Home</a></li>
    <li><a href="{{ url_for('main.show_elections') }}" >Elections</a></li>
    <li><a href="{{ url_for('main.show_representatives') }}" >Current Officials</a></li>
    <li><a href="{{ url_for('main.show_votehistory_blank') }}" >Vote History</a></li>
  </ul>
{% endblock %}
{% block body %}
  <br/>
  <div class="jumbotron">
    <h1>{% if current_user.is_authenticated() %} {{ current_user.username }}: {% endif %}Your vote counts</h1>
    <p>We want you to know who you're voting for, and understand why.</p>
    <p><a class="btn btn-primary btn-lg" role="button" href="{{ url_for('main.show_representatives') }}">Find your representatives</a></p>
</div>
{% endblock %}k

application/templates/layout.html
<!doctype html>
{% import "bootstrap/wtf.html" as wtf %}
<html lang="en">
  <head>
    <title>Vote Your Know</title>
    {% block style %}
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" >
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bootstrap-3.2.0-dist/css/bootstrap.min.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bootstrap-3.2.0-dist/css/bootstrap-theme.min.css') }}">
        <link rel=stylesheet type=text/css href="{{ url_for('static', filename='custom-css/sticky-footer.css') }}">
    {% endblock %}
    </head>
    <body>
      <div class="container">
        <div class="page-header">
          <h1>Vote Your Know <small>and know your vote!</small></h1>
          <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated() %}
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                  <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                </ul>
              </li>
            {% else %}
              <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
        {% block nav %}
          <ul class="nav nav-pills">
            <li><a href="{{ url_for('main.show_landing_page') }}" >Home</a></li>
            <li><a href="{{ url_for('main.show_elections') }}" >Elections</a></li>
            <li><a href="{{ url_for('main.show_representatives') }}" >Current Officials</a></li>
            <li><a href="{{ url_for('main.show_votehistory_blank') }}" >Vote History</a></li>
          </ul>
        {% endblock %}
        {% block content %}
          <div class="container">
            {% for message in get_flashed_messages() %}
              <br />
              <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
              </div>
            {% endfor %}
          </div>
        {% endblock %}
        {% block body %}
        {% endblock %}
      </div>
      <div class="footer">
        <div class="container">
          <p class="text-muted">&copy; Will Bastian 2014</p>
        </div>
      </div>
      <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
      <!-- Include all compiled plugins (below), or include individual files as needed -->
      <script src="static/bootstrap-3.2.0-dist/js/bootstrap.min.js"></script>
    </body>
  </html>

application/templates/show_representative_votehistory.html
{% extends "layout.html" %}
{% block nav %}
  <ul class="nav nav-pills">
    <li><a href="{{ url_for('main.show_landing_page') }}" >Home</a></li>
    <li><a href="{{ url_for('main.show_elections') }}" >Elections</a></li>
    <li><a href="{{ url_for('main.show_representatives') }}" >Current Officials</a></li>
    <li class="active"><a href="{{ url_for('main.show_votehistory_blank') }}" >Vote History</a></li>
  </ul>
{% endblock %}
{% block body %}
  {{ wtf.quick_form(lookupform) }}
  <br/>
  <div class="panel panel-success">
    {% if votehistory %}
    <h3 class="panel-heading">
    {{votehistory[0]['person']['name']}}
    </h3>
    <div class="panel-body">
      <div class="row">
        {% for vote in votehistory %}
          <div class="col-md-6">
            <div class="panel panel-default">
              {% if vote.get('full_bill') %}
                <h3 class="panel-heading">{{vote['full_bill']['title']}}</h3>
              {% else %}
                <h3 class="panel-heading">NO DATA HERE</h3>
              {% endif %}
              <div class="row">
                <div class="col-md-6">
                  
                </div>
                <div class="col-md-6">
                  
                  <div class="caption">
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

application/templates/show_representativeinfo.html
{% extends "layout.html" %}
{% block nav %}
  <ul class="nav nav-pills">
    <li><a href="{{ url_for('main.show_landing_page') }}" >Home</a></li>
    <li><a href="{{ url_for('main.show_elections') }}" >Elections</a></li>
    <li class="active"><a href="{{ url_for('main.show_representatives') }}" >Current Officials</a></li>
    <li><a href="{{ url_for('main.show_votehistory_blank') }}" >Vote History</a></li>
  </ul>
{% endblock %}
{% block body %}
  {{ wtf.quick_form(lookupform) }}
  <br/>
  <div class="panel panel-success">
    <h3 class="panel-heading">Offices</h3>
    {% for office in representatives["offices"] %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">{{office["name"]}}</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            {% for official_index in office["officialIndices"] %}
              <div class="col-md-6">
                <div class="thumbnail">
                  <h3>{{representatives["officials"][official_index]["name"]}}</h3>
                  <div class="row">
                    <div class="col-md-6">
                      <img style="max-height: 200px;" class="img-responsive img-rounded"src="{{representatives["officials"][official_index]["photoUrl"]}}" alt="">
                    </div>
                    <div class="col-md-6">
                      
                      <div class="caption">
                        
                        <p>Party: {{representatives["officials"][official_index]["party"]}}</p>
                        <p>
                        <a href="{{url_for('main.show_votehistory', firstname=representatives["officials"][official_index]['first_name'], lastname=representatives["officials"][official_index]['last_name']) }}">Vote History</a>
                        </p>
                        <p>
                        <div class="candidate-contact">
                          {% for url in representatives["officials"][official_index]["urls"] %}
                            <a style="word-wrap: break-word;" href="{{url}}">{{url}}</a>
                          {% endfor %}
                          {% for phone in representatives["officials"][official_index]["phones"] %}
                            <div class="phone-number">{{phone}}</div>
                          {% endfor %}
                        </div>
                        </p>
                        
                        <ul class="list-inline">
                          {% for social_media_channel in representatives["officials"][official_index]["channels"] %}
                            {% if social_media_channel["type"] == "Facebook" %}
                              <li><a href="http://facebook.com/{{social_media_channel["id"]}}"><img src="{{url_for('static', filename='Facebook-icon.png') }}"></a></li>
                            {% endif %}
                            {% if social_media_channel["type"] == "YouTube" %}
                              <li><a href="http://youtube.com/{{social_media_channel["id"]}}"><img src="{{url_for('static', filename='Youtube-icon.png') }}"></a></li>
                            {% endif %}
                            {% if social_media_channel["type"] == "Twitter" %}
                              <li><a href="http://twitter.com/{{social_media_channel["id"]}}"><img src="{{url_for('static', filename='Twitter-icon.png') }}"></a></li>
                            {% endif %}
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

application/templates/show_voterinfo.html
{% extends "layout.html" %}
{% block nav %}
  <ul class="nav nav-pills">
    <li><a href="{{ url_for('main.show_landing_page') }}" >Home</a></li>
    <li class="active"><a href="{{ url_for('main.show_elections') }}" >Elections</a></li>
    <li><a href="{{ url_for('main.show_representatives') }}" >Current Officials</a></li>
    <li><a href="{{ url_for('main.show_votehistory_blank') }}" >Vote History</a></li>
  </ul>
{% endblock %}
{% block body %}
  {{ wtf.quick_form(lookupform) }}
  <br/>
  {# {% if voterinfo["status"] == "success" %} #}
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">Polling Place</div>
          {% for polling_location in voterinfo["pollingLocations"] %}
            <address>
              <strong>{{polling_location["address"]["locationName"]}}</strong><br/>
              {{polling_location["address"]["line1"]}}
              {{polling_location["address"]["line2"]}}
              {{polling_location["address"]["line3"]}}
              {{polling_location["address"]["city"]}}
              {{polling_location["address"]["state"]}}
            </address>
            {{polling_location["notes"]}}
            {{polling_location["pollingHours"]}}
            {{polling_location["voterServices"]}}
            {{polling_location["startDate"]}}
            {{polling_location["endDate"]}}
          {% endfor %}
        </div>
      </div>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">Early Voting Location(s)</div>
          {% for early_vote_site in voterinfo["earlyVoteSites"] %}
            <address>
              <strong>{{early_vote_site["address"]["locationName"]}}</strong><br/>
              {{early_vote_site["address"]["line1"]}}
              {{early_vote_site["address"]["line2"]}}
              {{early_vote_site["address"]["line3"]}}
              {{early_vote_site["address"]["city"]}}
              {{early_vote_site["address"]["state"]}}
            </address>
            {{early_vote_site["notes"]}}
            {{early_vote_site["pollingHours"]}}
            {{early_vote_site["voterServices"]}}
            {{early_vote_site["startDate"]}}
            {{early_vote_site["endDate"]}}
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="panel panel-success">
      <h3 class="panel-heading">Referendums</h3>
        {% for referendum in voterinfo["referendums"] %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{{referendum["referendumTitle"]}}</h3>
            {{referendum["referendumSubtitle"]}}
          </div>
        </div>
        {% endfor %}
    </div>
    <div class="panel panel-success">
      <h3 class="panel-heading">Contests</h3>
      <form action="{{ url_for('main.save_voterinfo') }}" method="post" accept-charset="utf-8">
        <div class="input-group">
          <input type="text" class="form-control" name="vote_name" placeholder="...Enter saved filter name">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Save!</button>
          </span>
        </div><!-- /input-group -->     
      {% for contest in voterinfo["contests"] %}
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{{contest["type"]}} - {{contest["office"]}} - {{contest["level"]}}</h3>
          </div>
          <div class="panel-body">
            <div class="row">
              {% for candidate, candidate_detail in contest["candidates"].items() %}
                <div class="col-md-6">
                  <div class="thumbnail" style="min-height:230px;">
                    <h3>{{candidate}}</h3>
                    <div class="btn-group" data-toggle="buttons">
                      <label class="btn btn-primary">
                        <input type="checkbox" name="do_save" value="{{candidate}}|{{candidate_detail}}|{{contest["type"]}}|{{contest["office"]}}|{{contest["level"]}}"> Save Candidate
                      </label>
                    </div>
                    <div class="row">                                             
                      <div class="col-md-4">
                        Parties: <ul>{% for party in candidate_detail["party"] %} <li>{{party}}</li>  {% endfor %} </ul>
                      </div>
                      <div class="col-md-8">
                        <a style="word-wrap: break-word;" href="{{candidate_detail["candidateUrl"]}}">{{candidate_detail["candidateUrl"]}}</a>
                        <br>
                        <div class="phone-number">{{candidate_detail["phone"]}}</div>
                        <ul class="list-inline">
                          {% for social_media_channel in candidate_detail["channels"] %}
                            {% if social_media_channel["type"] == "Facebook" %}
                              <li><a href="{{social_media_channel["id"]}}"><img src="{{ url_for('static', filename='Facebook-icon.png') }}"></a></li>
                            {% endif %}
                            {% if social_media_channel["type"] == "YouTube" %}
                              <li><a href="{{social_media_channel["id"]}}"><img src="{{ url_for('static', filename='Youtube-icon.png') }}"></a></li>
                            {% endif %}
                            {% if social_media_channel["type"] == "Twitter" %}
                              <li><a href="{{social_media_channel["id"]}}"><img src="{{ url_for('static', filename='Twitter-icon.png') }}"></a></li>
                            {% endif %}
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      {% endfor %}

    </form>
    </div>    
  {# {% else %}
    Please enter a valid address
  {% endif %} #}
{% endblock %}